name: CI-build-and-test

#on: 
#  push:
#    # To run on all branches, but not 'master'.
#    branches:
#      -  '*'
#      - '!master'
#  pull_request:
on: [push]

  
jobs:
  build:
    name: CI-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    #env:
    #  buildDir: '${{ github.workspace }}/build'
    
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v1
    
    #- name: build and test
    #  uses: lukka/run-cmake@v3
    #  with:
    #    cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
    #    cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
    #    buildDirectory: '${{ runner.workspace }}/build'
    #    buildWithCMakeArgs: "--target check"

    - name: make build dir
      run: mkdir ${{github.workspace}}/build


    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory.
      run: cmake -B ${{github.workspace}}/build


    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build

    - name: package
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build --target package


    - name: archive build output
      uses: actions/upload-artifact@v1
      with:
        name: arti-${{ matrix.os }}
        path: ${{ github.workspace }}/build/out/c*

